name: Reusable workflow
on:
  workflow_call:
    inputs:
      input1:
        type: string
        required: true
    outputs:
      test-output:
        description: "LOL KEK"
        value: ${{ jobs.reusable.outputs.test-output }}

jobs:
  reusable:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epam/hub-toolbox:base
      volumes:
        - /workspace:${{ github.workspace }}
    outputs:
      test-output: ${{ steps.test.outputs.test-output }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Test commands
        run: |-
          pwd
          ls -la
          env | sort
          hubctl version
          echo "${{ github.workspace }}"

      - name: Outputs
        id: test
        run: |-
          echo test-output="this is test output with input value ${{ inputs.input1 }}" >> $GITHUB_OUTPUT
