name: Reusable workflow
on:
  workflow_call:
    inputs:
      verb:
        type: string
        description: 'Action to run: deploy or undeploy'
        default: deploy
      workdir:
        type: string
        description: Directory where to run hubctl commands
        required: true
      toolbox-image:
        type: string
        description: Toolbox image with tag
        default: ghcr.io/epam/hub-toolbox:base
    outputs:
      stack-outputs:
        value: ${{ jobs.reusable.outputs.stack-outputs }}

jobs:
  reusable:
    runs-on: ubuntu-latest
    container: ${{ inputs.toolbox-image }}
    outputs:
      stack-outputs: ${{ steps.stack-outputs.outputs.stack-outputs }}
    env:
      HUB_AUTOCONFIGURE: "0"
      INTERACTIVE: "0"
      HUB_INTERACTIVE: "0"
      HUB_DEPLOY_PROFILE: "local"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Init
        working-directory: ${{ inputs.workdir }}
        run: hubctl stack init

      - name: Configure
        working-directory: ${{ inputs.workdir }}
        run: hubctl stack configure

      - name: Deploy stack
        working-directory: ${{ inputs.workdir }}
        run: hubctl stack ${{ inputs.verb }}

      - name: Outputs
        id: stack-outputs
        working-directory: ${{ inputs.workdir }}
        run: |-
          echo stack-outputs="$(hubctl show --format json | jq -crM)" >> $GITHUB_OUTPUT
