name: Reusable workflow
on:
  workflow_call:
    outputs:
      stack-outputs:
        value: ${{ jobs.reusable.outputs.stack-outputs }}

jobs:
  reusable:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epam/hub-toolbox:base
      volumes:
        - /workspace:${{ github.workspace }}
    outputs:
      stack-outputs: ${{ steps.stack-outputs.outputs.stack-outputs }}
    env:
      HUB_AUTOCONFIGURE: "0"
      INTERACTIVE: "0"
      HUB_INTERACTIVE: "0"
      HUB_DEPLOY_PROFILE: "local"
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Init stack
        working-directory: ./stacks/second
        run: |-
          hubctl stack init

      - name: Configure stack
        working-directory: ./stacks/second
        run: |-
          hubctl stack configure

      - name: Deploy stack
        working-directory: ./stacks/second
        run: |-
          hubctl stack deploy

      - name: Outputs
        id: stack-outputs
        run: |-
          echo hubctl-show="$(hubctl show --format json | jq -crM)" >> $GITHUB_OUTPUT
