name: 'Test reusable workflow'
on:
  workflow_dispatch:
    inputs:
      verb:
        type: choice
        options:
          - deploy
          - undeploy
        description: Deploy or undeploy
        default: deploy
      toolbox-image:
        type: choice
        options:
          - ghcr.io/epam/hub-toolbox:base
          - ghcr.io/epam/hub-toolbox:aws
          - ghcr.io/epam/hub-toolbox:gcp
          - ghcr.io/epam/hub-toolbox:azure
        description: Toolbox image
        default: ghcr.io/epam/hub-toolbox:base

jobs:
  dotenv:
    runs-on: ubuntu-latest
    steps:
      - id: dotenv
        name: Get dotenv files
        run: |
          cat << EOF >> $GITHUB_WORKSPACE/.env
            A=1
            B=2
            C=3
            D=4
            E=5
          EOF
      - uses: actions/upload-artifact@v3
        with:
          name: dotenv
          path: ${{ github.workspace }}/.env

  first-stack:
    uses: ./.github/reusable/reusable-workflow.yml
    needs: dotenv
    with:
      workdir: ./stacks
      verb: ${{ inputs.verb }}
      toolbox-image: ${{ inputs.toolbox-image }}

  second-stack:
    uses: ./.github/reusable/reusable-workflow.yml
    needs: dotenv
    with:
      workdir: ./stacks/second
      verb: ${{ inputs.verb }}
      toolbox-image: ${{ inputs.toolbox-image }}

  test-outputs:
    runs-on: ubuntu-latest
    needs: [first-stack, second-stack]
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3

    - name: Show outputs
      run: |-
        echo "${{ needs.first-stack.outputs.stack-outputs }}"
        echo "${{ needs.second-stack.outputs.stack-outputs }}"
