name: 'Test reusable workflow'
on:
  workflow_dispatch: {}

jobs:
  simple-stack:
    uses: ./.github/workflows/reusable-workflow.yml

  test-outputs:
    runs-on: ubuntu-latest
    needs: simple-stack
    container: ghcr.io/epam/hub-toolbox:aws
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3

    - name: Show outputs
      run: |-
        echo "${{ needs.simple-stack.outputs.stack-outputs }} | jq '.'"
