name: 'Test'

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment selector'
        required: true
      stringInput:
        description: 'This is string input'
        required: false
        default: 'stringInput'
      booleanInput:
        type: boolean
        description: 'This is boolean input'
        required: false
        default: false
      choiseInput:
        type: choice
        description: 'This is choise input'
        required: false
        options:
          - choise1
          - choise2
          - choise3
        default: 'choise2'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.environment }}
    steps:
      - name: Before
        run: |
          echo "$MY_ENV_VAR_1"
      - name: Test
        run: |
          echo '${{ toJson(vars) }}' | jq -crM 'to_entries | map("\(.key)=\"\(.value|tostring)\"") | .[]' >> $GITHUB_ENV
          echo "right after = $MY_ENV_VAR_1"
      - name: After
        run: |
          echo "$MY_ENV_VAR_1"

  test-condition:
    runs-on: 'ubuntu-latest'
    if: inputs.booleanInput
    steps:
      -
        id: 'test'
        name: 'Test inputs with conditions'
        env:
          STRING_INPUT: ${{ inputs.stringInput }}
          BOOLEAN_INPUT: ${{ inputs.booleanInput }}
          CHOISE_INPUT: ${{ inputs.choiseInput }}
        run: |
          echo "STRING_INPUT=$STRING_INPUT"
          echo "BOOLEAN_INPUT=$BOOLEAN_INPUT"
          echo "CHOISE_INPUT=$CHOISE_INPUT"

  test-negative-condition:
    runs-on: 'ubuntu-latest'
    if: '!inputs.booleanInput'
    steps:
      -
        id: 'test'
        name: 'Test inputs'
        env:
          STRING_INPUT: ${{ inputs.stringInput }}
          BOOLEAN_INPUT: ${{ inputs.booleanInput }}
          CHOISE_INPUT: ${{ inputs.choiseInput }}
        run: |
          echo "STRING_INPUT=$STRING_INPUT"
          echo "BOOLEAN_INPUT=$BOOLEAN_INPUT"
          echo "CHOISE_INPUT=$CHOISE_INPUT"
